spring:
  data:
    mongodb:
      authentication-database: youtubeVideoDatabase
      username: youtube
      password: youtube
      database: youtubeVideoDatabase
      port: 27017
      host: localhost